service: random-mdn # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs14.x

functions:
  tweet:
    handler: handler.tweet
    events:
      - schedule: rate(4 hours)
    environment:
      CONSUMER_KEY: ${env:CONSUMER_KEY}
      CONSUMER_SECRET: ${env:CONSUMER_SECRET}
      ACCESS_TOKEN: ${env:ACCESS_TOKEN}
      ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
      NODE_ENV: ${env:NODE_ENV}
